/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const before_Invoices_Create_Update = require('./code/before-invoices-create-update');

class cOE_DEMOSrv extends LCAPApplicationService {
    async init() {

        this.before(['CREATE', 'UPDATE'], 'Invoices', async (request) => {
            await before_Invoices_Create_Update(request);
        });

        return super.init();
    }
}


module.exports = {
    cOE_DEMOSrv
};